### ISSUE TITLE
"Include" throws NotSupportedException

### ISSUE THREAD

**Issue by Int32Overflow** [mgernand/LiteDB.Queryable#19]
Example code:
```csharp
LiteDatabaseAsync database = new LiteDatabaseAsync("test.db");
ILiteCollectionAsync<Person> collection = database.GetCollection<Person>("people");
IQueryable<Person> queryable = collection.AsQueryable();
var result = queryable.Include(i => i.ChildItems).ToListAsync()
```

The following error message is thrown:
`System.NotSupportedException: 'The LINQ extension method 'Include' is not supported.'`

![grafik](https://github.com/mgernand/LiteDB.Queryable/assets/20139038/ba0ddb78-c00b-4f23-8e82-2e4f43e4b002)

**Comment by mgernand** [comment]
Hi! Thanks for your contribution. 🙂
